services:
  mysql:
    image: mysql # If you control+click this you can see the official MySQL image.
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    deploy: # The below is to stop the database from destroying your machine and devouring everything.
      resources:
        limits:
          cpus: "0.50" # Limit to 50% of a single CPU core
          memory: "512M" # Limit to 512MB of RAM